/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AtividadeSeis;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        
        Scanner leitor = new Scanner(System.in);
        
        String nomeAluno;
        int nota1;
        int nota2;
        int nota3;
        int mediaFinal;
        
        
        
        System.out.println("Digite seu nome");
        nomeAluno = leitor.nextLine();

        System.out.println("Digite a nota 1:");
        nota1 = leitor.nextInt();

        System.out.println("Digite a nota 2:");
        nota2 = leitor.nextInt();

        System.out.println("Digite a nota 3:");
        nota3 = leitor.nextInt();
        
        mediaFinal = (nota1 + nota2 + nota3) / 3;
        
        System.out.println("Sua média é: " + mediaFinal);
        
    }
}
